### ISSUE TITLE
Fix feedback on R CMD CHECK. There should be zero errors, warnings and notes.

### ISSUE THREAD

**Issue by nikolase90** [NorskRegnesentral/shapr#12]

**Comment by JensWahl** [comment]
To avoid notes of the type *no visible binding for global variable* from ggplot one can add a `global_vars.R` file (like [this](https://github.com/IndrajeetPatil/ggstatsplot/blob/master/R/global_vars.R)), where you add all variables used. Another option is to add all variables used by ggplot at the top of the function and give them a `NULL` value. Any thoughts?

**Comment by nikolase90** [comment]
We have sort of decided in the former solution, see https://github.com/NorskRegnesentral/shapr/blob/master/R/zzz.R.
