### ISSUE TITLE
Update examples to new package style

### ISSUE THREAD

**Issue by martinju** [NorskRegnesentral/shapr#121]
Currently, some of the examples under inst/scripts still follow the style from the old package.

**Comment by nikolase90** [comment]
I think we should remove `inst/scripts/example.R` (this is basically what we cover in the vignette), and update the script that compares the method with Lundberg's python package. Agree?

**Comment by martinju** [comment]
Yes! I can do it.

**Comment by nikolase90** [comment]
Perfect!
