### ISSUE TITLE
Fix redundant arguments

### ISSUE THREAD

**Issue by martinju** [NorskRegnesentral/shapr#138]
A list of potentially redundant function arguments that we could remove to simplify code.

- [x] We may delete the `reduce_dim` argument of `feature_combinations` (always set it to TRUE)
- [ ] If we delete the `reduce_dim` argument, we probably don't need the `use_shapley_weights_in_W` argument in `weight_matrix`, as the no-column is always 1 (check!!!), and then we can simplify this code by always using the `shapley_weight` column only as the weights.
- [x] Remove `type` in `inv_gaussian_transform`

**Comment by nikolase90** [comment]
Fixed with #141 and #142 .
