### ISSUE TITLE
Add vignette of methodology/package

### ISSUE THREAD

**Issue by nikolase90** [NorskRegnesentral/shapr#17]
I made a template with https://github.com/NorskRegnesentral/shapr/tree/nikolai/add_vignette. You could continue pushing to this branch once you have the time work on this. 

Some examples of vignettes: 
- https://github.com/thomasp85/lime
- https://github.com/osorensen/BayesMallows

**Comment by martinju** [comment]
List of features for the vignette

- [ ] Short intro with some info on Shapley values for prediction explanation, mentioning that we account for dependence which the original kernelSHAP implementation doesn't
- [ ] Overview of main functions
- [ ] "Technical" description of the various approximation functions (copy some content from paper)
- [ ] Compare our version of independence kernelSHAP with the original implementation checking that we get (essentially) the same results. 
- [ ] Include readme example of running our method 
- [ ] If we have time and bother: An additional, small simulation run with know truth, comparing our methods with independence (and/or TreeSHAP) like in the paper.
- [ ] Reference paper for further details and comparisons

**Comment by martinju** [comment]
Ref #59 I will prepare a code chunk comparing Lundberg's implementation of KernelSHAP with a special case of implementation to check that we get comparable results. Will use example from readme.
