### ISSUE TITLE
[review-frycast] LICENSE

### ISSUE THREAD

**Issue by nikolase90** [NorskRegnesentral/shapr#175]
@frycast The reason why the description file states the following 
```
License: MIT + file LICENSE
```
is described in http://r-pkgs.had.co.nz/description.html#license. See the section with MIT license. 

You could also see a similar discussion here: https://github.com/openjournals/joss-reviews/issues/1863.

**Comment by nikolase90** [comment]
@frycast Let us know if you have any further comments about this 👍 Otherwise we'll just close it and move forward. Thanks!

**Comment by martinju** [comment]
Closed as @frycast approved the current license version, ref https://github.com/openjournals/joss-reviews/issues/2027#issuecomment-581192895

**Comment by martinju** [comment]
Close #171 and this issue as @frycast approved the current license version, ref https://github.com/openjournals/joss-reviews/issues/2027#issuecomment-581192895
