### ISSUE TITLE
Vignette fails with uninformative error

### ISSUE THREAD

**Issue by frycast** [NorskRegnesentral/shapr#176]
When package gbm is missing, the [vignette](https://github.com/NorskRegnesentral/shapr/blob/master/vignettes/understanding_shapr.Rmd) fails to knit, and the error message doesn't make it very clear that gbm is the culprit.

I suggest  adding `library(gbm)` somewhere before line 399, so that a more informative error message is printed.

**Comment by nikolase90** [comment]
Thanks for catching that one!
