### ISSUE TITLE
Bump version to 0.1.1

### ISSUE THREAD

**Issue by nikolase90** [NorskRegnesentral/shapr#193]
@martinju Could you fix that? Also do a release on Github as you previously did with 0.1.0?

**Comment by martinju** [comment]
Yep!

**Comment by nikolase90** [comment]
Sweet. Could you also check if we need to update the date stated in the paper?

**Comment by nikolase90** [comment]
Never mind that last one.

**Comment by nikolase90** [comment]
@martinju Don't forget the `NEWS.md` 👍

**Comment by martinju** [comment]
I'll make a GitHub release when this is merged with the same content as NEWS.md. 
Can you handle the Zenodo/figshare afterwords?
