### ISSUE TITLE
Testing of package using docker

### ISSUE THREAD

**Issue by nikolase90** [NorskRegnesentral/shapr#200]
|name               |description                                      |cran-name                         |rversion  |os-type |cpu-type |os-info                  |compilers                                      |docker-image       |sysreqs-platform          |categories |node-labels |queue |output-parser |macos-version |
|:------------------|:------------------------------------------------|:---------------------------------|:---------|:-------|:--------|:------------------------|:----------------------------------------------|:------------------|:-------------------------|:----------|:-----------|:-----|:-------------|:-------------|
|debian-clang-devel |Debian Linux, R-devel, clang, ISO-8859-15 locale |r-devel-linux-x86_64-debian-clang |r-devel   |Linux   |x86_64   |Debian GNU/Linux testing |clang version 7.0.1-8 (tags/RELEASE_701/final) |debian-clang-devel |linux-x86_64-debian-clang |Linux      |linux       |linux |NA            |NA            |
|debian-gcc-devel   |Debian Linux, R-devel, GCC                       |r-devel-linux-x86_64-debian-gcc   |r-devel   |Linux   |x86_64   |Debian GNU/Linux testing |gcc version 8.3.0 (Debian 8.3.0-5)             |debian-gcc-devel   |linux-x86_64-debian-gcc   |Linux      |linux       |linux |NA            |NA            |
|debian-gcc-patched |Debian Linux, R-patched, GCC                     |r-patched-linux-x86_64            |r-patched |Linux   |x86_64   |Debian GNU/Linux testing |gcc version 8.3.0 (Debian 8.3.0-5)             |debian-gcc-patched |linux-x86_64-debian-gcc   |Linux      |linux       |linux |NA            |NA            |
|debian-gcc-release |Debian Linux, R-release, GCC                     |r-release-linux-x86_64            |r-release |Linux   |x86_64   |Debian GNU/Linux testing |gcc version 8.3.0 (Debian 8.3.0-5)             |debian-gcc-release |linux-x86_64-debian-gcc   |Linux      |linux       |linux |NA            |NA            |
|fedora-clang-devel |Fedora Linux, R-devel, clang, gfortran           |r-devel-linux-x86_64-fedora-clang |r-devel   |Linux   |x86_64   |Fedora 24                |clang version 3.8.0; GNU Fortran 6.1.1         |fedora-clang-devel |linux-x86_64-fedora-clang |Linux      |linux       |linux |NA            |NA            |
|fedora-gcc-devel   |Fedora Linux, R-devel, GCC                       |r-devel-linux-x86_64-fedora-gcc   |r-devel   |Linux   |x86_64   |Fedora 24                |GCC 6.1.1                                      |fedora-gcc-devel   |linux-x86_64-fedora-gcc   |Linux      |linux       |linux |NA            |NA            |

**Comment by nikolase90** [comment]
https://cran.r-project.org/web/packages/rhub/vignettes/local-debugging.html

**Comment by nikolase90** [comment]
@martinju Not much progress here. I saw that R 4.0.0 was going to be released, and I decided to wait for that. So I should get up to speed on things again this week.

**Comment by martinju** [comment]
I don't think this currently is worth the effort as GitHub actions, r-hub, winbuilder and local debugging on windows and ubuntu serves the purpose. 

**IF** we run into OS-spesific problems we could re-visit this.
