### ISSUE TITLE
Unclear error message when using unnamed matrix

### ISSUE THREAD

**Issue by frycast** [NorskRegnesentral/shapr#202]
In this example the matrices x_train and x_test will have no column names:

```data("Boston", package = "MASS")
x_var <- c("lstat", "rm", "dis", "indus")
y_var <- "medv"
ind_x_test <- 1:6
x_train <- as.matrix(Boston[-ind_x_test, x_var])
y_train <- Boston[-ind_x_test, y_var]
x_test <- as.matrix(Boston[ind_x_test, x_var])

# Later the error message will not say the matrix must have column names
colnames(x_train) <- NULL
colnames(x_test) <- NULL

model <- xgboost(
  data = x_train,
  label = y_train,
  nround = 20,
  verbose = FALSE
)
explainer <- shapr(x_train, model)
p <- mean(y_train)
explanation <- explain(
  x_test,
  approach = "empirical",
  explainer = explainer,
  prediction_zero = p
)
```
We get the following error, which makes it hard to tell the problem:

**Error in matrix(NA, ncol = n_col, nrow = no_empirical) : 
  non-numeric matrix extent**

**Comment by martinju** [comment]
Thanks for catching and reporting this!

We had a check of whether the column names stored by the model are included to those passed to `shapr`, but both being NULL incorrectly passed the test. Should be fixed in #203.
