### ISSUE TITLE
Failing to install shapr: " cannot remove prior installation of package 'Rcpp' "

### ISSUE THREAD

**Issue by mlds2020** [NorskRegnesentral/shapr#216]
I am having trouble installing shapr onto a completly new R anaconda environment (with RTools installed).
I use the line suggested in the README:

`devtools::install_github("NorskRegnesentral/shapr", dependencies = TRUE)`

which yields the following error message:

> package 'Rcpp' successfully unpacked and MD5 sums checked
> Error: Failed to install 'shapr' from GitHub:
>   (konvertiert von Warnung) cannot remove prior installation of package 'Rcpp'
> Traceback:
> 
> 1. devtools::install_github("NorskRegnesentral/shapr", 
>  .     dependencies = TRUE)
> 2. pkgbuild::with_build_tools({
>  .     ellipsis::check_dots_used(action = getOption("devtools.ellipsis_action", 
>  .         rlang::warn))
>  .     {
>  .         remotes <- lapply(repo, github_remote, ref = ref, subdir = subdir, 
>  .             auth_token = auth_token, host = host)
>  .         install_remotes(remotes, auth_token = auth_token, host = host, 
>  .             dependencies = dependencies, upgrade = upgrade, force = force, 
>  .             quiet = quiet, build = build, build_opts = build_opts, 
>  .             build_manual = build_manual, build_vignettes = build_vignettes, 
>  .             repos = repos, type = type, ...)
>  .     }
>  . }, required = FALSE)
> 3. withr::with_path(rtools_path(), code)
> 4. force(code)
> 5. install_remotes(remotes, auth_token = auth_token, host = host, 
>  .     dependencies = dependencies, upgrade = upgrade, force = force, 
>  .     quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, 
>  .     build_vignettes = build_vignettes, repos = repos, type = type, 
>  .     ...)
> 6. tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) {
>  .     stop(remote_install_error(remotes[[i]], e))
>  . })
> 7. tryCatchList(expr, classes, parentenv, handlers)
> 8. tryCatchOne(expr, names, parentenv, handlers[[1L]])
> 9. value[[3L]](cond)

Did anyone have a similar error message?

**Comment by martinju** [comment]
Seems installing Rcpp is failing due to a different (older?) version of Rcpp? I would try to manually remove your current installation of Rcpp and repeat the procedure.

**Comment by mlds2020** [comment]
That's weird, given I just installed R on a completely new anaconda virtual env.
I did run 
`remove.packages(c("Rcpp"))`
but I doesn't seem to help.

I also use the `remotes `library now instead of `devtools`, as per your recent change in the README.

Output:
> There is a binary version available but the source version is later:
>           binary source needs_compilation
> backports  1.1.7  1.1.8              TRUE
> 
> package 'Rcpp' successfully unpacked and MD5 sums checked
> Error: Failed to install 'shapr' from GitHub:
>   (konvertiert von Warnung) cannot remove prior installation of package 'Rcpp'
> Traceback:
> 
> 1. remotes::install_github("NorskRegnesentral/shapr", ref = "ctree", 
>  .     dependencies = TRUE)
> 2. install_remotes(remotes, auth_token = auth_token, host = host, 
>  .     dependencies = dependencies, upgrade = upgrade, force = force, 
>  .     quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, 
>  .     build_vignettes = build_vignettes, repos = repos, type = type, 
>  .     ...)
> 3. tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) {
>  .     stop(remote_install_error(remotes[[i]], e))
>  . })
> 4. tryCatchList(expr, classes, parentenv, handlers)
> 5. tryCatchOne(expr, names, parentenv, handlers[[1L]])
> 6. value[[3L]](cond)

Maybe one of your dependencies depends on a different version of Rcpp? Thus it is trying to download Rcpp twice, in different versions?

I am using Windows 10, if that is of any help.

**Comment by martinju** [comment]
Yes, my hunch is also that it had to do with other packages depending on newer Rcpp versions. Unfortunately I am on vacation for the rest of the week without a computer to test things on, so I can't check it or try to reproduce this at the moment. We have CI-tests on Windows 10 with R 4.0 running fine two days ago. That installs Rcpp 1.0.5 from CRAN. Are the other dependencies passing through and getting installed? If so you could install Rcpp 1.0.5 manually and then rerun with dependencies=FALSE. You may also want to double check that R has the required permission on the folder where you are installing packages.

**Comment by mlds2020** [comment]
All other dependencies installed correctly. Manually installing Rcpp and running the line again with `dependencies=False` seemed to have worked out. Thanks!
