### ISSUE TITLE
When should one set sample=TRUE or sample=FALSE in the ctree-explainer?

### ISSUE THREAD

**Issue by mlds2020** [NorskRegnesentral/shapr#217]
All the info I could find on the parameter was in the docstring for `explain.ctee`:

> #' @param sample Boolean. If true, then method samples from the terminal node in the tree. If false, then just takes all observations in the node.

But I don't seem to find any suggestion when/why to set sample to TRUE or FALSE? On review of the [ctree-shapr-paper](https://arxiv.org/pdf/2007.01027.pdf) I didn't find any suggestions either.

Would always leaving sample=TRUE (as per default) be alright?

**Comment by martinju** [comment]
Leaving it at the default is perfectly fine

Using all samples may however give slightly more stable estimates and should give you the same (in the limit) as if you sampled a very large number of observations. If you dont have too many training observations and/or very narrow trees (leading to many observations in the terminal nodes) I would recommend sample = FALSE. While it gives you a trade off between speed and accuracy/stability, I dont think it is a very important parameter. 

I guess we should update the man file with this advice.

**Comment by martinju** [comment]
Hi again. Going back to the code, I realized that even if you set `sample=TRUE`, we only do sampling when there are more than `n_samples` (input to `prepare_data` passed on from `explain` and defaults to 1000). Thus, even if you have a small data set or narrow trees, you can safely use the default `sample=TRUE` to get the best performance. The help function will be updated with this within a few days.
