### ISSUE TITLE
Fix CRAN submission feedback

### ISSUE THREAD

**Issue by martinju** [NorskRegnesentral/shapr#225]
Just got the following feedback from CRAN. I will attempt to fix these issues tomorrow in separate commits to be pushed to PR #220. I might ask you for advice on some of them @nikolase90 

- [x] Please reduce the length of the title to less than 65 characters. (a5490a2)

- [x] Using foo:::f instead of foo::f allows access to unexported objects.
It should not be used in other context and is generally not recommended, 
as the semantics of unexported objects may be changed by the package 
author in routine maintenance. (12da56b)

- [x] You have examples for unexported functions.
Please either omit these examples or export these functions. (12da56b)

- [x] You write information messages to the console that cannot be easily 
suppressed. It is more R like to generate objects that can be used to 
extract the information a user is interested in, and then print() that 
object. Instead of print()/cat() rather use message()/warning() or 
if(verbose)cat(..) (or maybe stop()) if you really have to write text to 
the console. (except for print, summary, interactive functions) (eae6289)

- [x] Please do not install packages in your functions, examples or vignette. 
This can make the functions,examples and cran-check very slow. (70987c9)

- [x] Please always add all authors, contributors and copyright holders in the 
Authors@R field with the appropriate roles.
e.g.: Norsk Regnesentral (4ba2219)

**Comment by nikolase90** [comment]
I would just remove the examples for the unexported functions. Just search for :::.

**Comment by nikolase90** [comment]
And replace print with message.

**Comment by martinju** [comment]
@nikolase90 I have done most of this already :-)

**Comment by nikolase90** [comment]
Nice. Didn't check the commits. And we agreed on everything 😃

**Comment by martinju** [comment]
Can't figure out what he refers to regarding "Please do not install packages in your functions, examples or vignette.
This can make the functions,examples and cran-check very slow.". Might be the devel scripts (not functions) under inst which I forgot to remove before submission.

**Comment by martinju** [comment]
I am done with the revision, and the final tests are now running. Do you want to take a quick look before I resubmit @nikolase90 ?

**Comment by nikolase90** [comment]
Left some comments in the PR. Otherwise, looks good to me!

**Comment by martinju** [comment]
Did you @nikolase90 ? I did not find any comments from you... I've seen the linting and will fix that.

**Comment by martinju** [comment]
Bummer! Tried to resubmit to CRAN: "Error: Submission failed: The submission team is on vacation from Aug 14, 2020 to Aug 24, 2020. During this time the submission of packages is not possible.
Sorry for any inconvenience. "

I will submit this Aug 24 then.
