### ISSUE TITLE
Error in explain()

### ISSUE THREAD

**Issue by ajoules** [NorskRegnesentral/shapr#260]
Running example code on an xgboost model:
explanation <- explain(
  x_test, 
  approach = "empirical",
  explainer = explainer,
  prediction_zero = p0
)

Produces error:
Error in mahalanobis_distance_cpp(featureList = list_features, Xtrain_mat = as.matrix(x_train),  : 
  Cube::init(): requested size is too large

Debug highlights error at 'dt <- prepare_data(explainer, ...)'

I'd appreciate any help as debug cannot be ran on 'prepare_data.empirical'

**Comment by martinju** [comment]
Hi!

Seems like the c++ code is complaining about too high dimension.
What is the dimension of you training data and data to explain?

**Comment by ajoules** [comment]
Hi! Thanks for getting to me so quickly!

25 features and 4483 observations. The code runs perfectly with example data.

**Comment by martinju** [comment]
Hmm. Do you have categorical features that you handle with our make_dummies function? In that case the actual number of features would be much larger. If not, try running with just say 100 training data (the actual model could be trained with all data, but pass just 100 observations to shapr) and 10 data to be explained. If that also gives the same error message, please post minimal reproducable example or at least paste your full code here.

**Comment by ajoules** [comment]
This solved the original error, thank you! I have a new error now:

*Error in mahalanobis_distance_cpp(featureList = list_features, Xtrain_mat = as.matrix(x_train),  : 
  chol(): decomposition failed*

**Code:**
```javascript

# run model
model <- xgboost(
  data = x_train,
  label = y_train$q8needio,
  nround = 20,
  verbose = FALSE
)

p <- get_base_score_prop(df, "outcome") # my function

explainer <- shapr(x_train[1:100,], model, n_combinations = 10000)

explanation <- explain(
  x_test[1:10,],
  approach = "empirical",
  explainer = explainer,
  prediction_zero = p
)
```

Can I 'debug' this code in R? I have failed to do so via debug(prepare_data.empirical) as object 'prepare_data.empirical' not found. 

I really appreciate your continued help, shapr is a great package - thank you!

**Comment by martinju** [comment]
Is the covariance matrix of your data positive definite? The error suggests it isn't. This is a problem when working with covariance matrix which is used to estimate the conditional distributions of your data. I realize we should have better error messages for these types of errors.

I never use the "debug" function manually, but I think you can work with it using just debug(prepare_data). ".empirical" just specifies the class method. 

To help you further it would be way easier if you could post a sample of your data + code that reproduces this.

**Comment by ajoules** [comment]
Thank you for your continued help! 

I've now given up in R and will switch to python for the analysis - but thank you, I really appreciate it! Sorry I couldn't provide the data as I do not own it. 

If I do come back to this and find a workaround, I will share!

**Comment by louisethvdb** [comment]
Hi! 

I have the same error and checked whether my covariance matrix of my data is positive definite. It is not as the error suggests. Would it then be impossible to apply shapr on this data? 

Thanks very much in advance!
