### ISSUE TITLE
Unnecessary computation of inverse

### ISSUE THREAD

**Issue by niklasfries** [NorskRegnesentral/shapr#280]
`src/weighted_matrix.cpp:72`:

`    R = inv(X.t() * Z) * X.t();` should be `    R = solve(X.t() * Z, X.t());`

This probably doesn't matter for the amounts of data the rest of the implementation is scaled for, but it's good practice and fixed a problem I had with an ill-conditioned matrix.

**Comment by martinju** [comment]
Thanks! We are working with the scalability of the whole package, so all improvements (even minor ones like this) is very welcome :-) 
I'll update this in a PR next week or so.

**Comment by AtroXWorf** [comment]
@martinju Have you had time to change the above mentioned line?
