### ISSUE TITLE
Will the library be made availble in Python as well?

### ISSUE THREAD

**Issue by trc729** [NorskRegnesentral/shapr#342]

**Comment by martinju** [comment]
Yes, finalizing the first version for public testing as we speak.

Follow this PR (will be updated soon) to stay updated: https://github.com/NorskRegnesentral/shapr/pull/325

**Comment by martinju** [comment]
Just pushed to master, see https://github.com/NorskRegnesentral/shapr/tree/master/python.

**Comment by trc729** [comment]
thank you very much!
