### ISSUE TITLE
Adding support for TensorFlow/Keras - anticipated challenges?

### ISSUE THREAD

**Issue by rawanmahdi** [NorskRegnesentral/shapr#343]
Hi! 
I'm interested in contributing by implementing support for keras models in the python version. Just curious, is there any reason why it hasn't yet been done? Any anticipated challenges with such implementation? 
Looking forward to contributing, 
Rawan

**Comment by martinju** [comment]
Great! Feel free to submit a PR. There is no reason it has not already been done, other than the python version being quite fresh and that python is not my main language.
