### ISSUE TITLE
Feature classes extracted from the model contains NA

### ISSUE THREAD

**Issue by aliamini-uq** [NorskRegnesentral/shapr#374]
Dear SHAPR,

I am new to this amazing package. I am sure that there is not any NA input in my data, but I see the following error:

```
Note: Feature classes extracted from the model contains NA.
Assuming feature classes from the data are correct.
```

Would you please help?

Best,
A

**Comment by martinju** [comment]
Hi

This is just a warning saying that an internal check that the features in your data (x_explain and x_train) and those specified in the supplied model could not be carried out. This happens as shapr was not able to retrieve the feature information from the model object. 

If you know what you are doing regarding which x_train/x_explain vs your model, this is nothing to worry about. 
I realize we should make the warning message more informative.

**Comment by aliamini-uq** [comment]
Dear Martin,

Many thanks for the clarification. You did a great job on `shapr` package.

Kind regards,
A
