### ISSUE TITLE
Multiclass Dataset by Applying SHAPR Package

### ISSUE THREAD

**Issue by AbdollahiAz** [NorskRegnesentral/shapr#378]
Hello, 

Is it possible to use the SHAPR package for dataset with multiclass (more than > 2 class; such as IRIS dataset)? I have a data set with 6 classes. I decide to apply SHAPR. Please give me suggestions to solve my problem.
Thank you for your consideration.

**Comment by martinju** [comment]
It is almost possible, but not quite as of know. You better split it up into multiple binary classifications when you are explaining them.
