### ISSUE TITLE
Comparing different dependency-aware approaches when the size of x_explain is large

### ISSUE THREAD

**Issue by aliamini-uq** [NorskRegnesentral/shapr#387]
Dear @martinju,

Thanks again for introducing `shapr` package.
Inspired by [Using Shapley Values and Variational Autoencoders to Explain Predictive Models with Dependent Mixed Features](https://www.jmlr.org/papers/v23/21-1413.html), I want to compare the performance of different dependency modeling approaches with Abalone dataset. In this paper, the sizes of  x_train and x_explain are 4077 and 100, respectively. However, I **want to increase the size of x_explain to 1200**. Based on issue #370, it seems there is a limit on the size of x_explain equal to 200. Would you please help me what should I do? My ultimate goal is to compare the performance of different approaches (e.g., `independence`, `ctree`, `vaeac`, and `empirical`) using `plot_MSEv_eval_crit()`.
Last but not least, I am most grateful for your priceless time in advance.

Kind regards,
A

**Comment by aliamini-uq** [comment]
Dear @martinju,

I will be honored if you take a look at my problem. 

Kind regards,
A

**Comment by martinju** [comment]
There is no limit on the size of x_explain. Just increase n_batches accordingly and should be fine (in theory). If you want to be on the safe side (not risiking losing anything) you can pass just a few x_explain at a time.
