### ISSUE TITLE
Dependency-aware approaches with one-hot encoded data

### ISSUE THREAD

**Issue by aliamini-uq** [NorskRegnesentral/shapr#388]
Dear @LHBO,

Many thanks for adding `vaeac` approach to the `shapr`  package. According to issue #385:  

> In the developer version of `shapr` here at this GitHub repository, both the `independence` and `vaeac` methods support categorical data. The former handles the levels directly, while `vaeac` will one-hot-encode the categorical features internally to support categorical data. Thus, the user does not have to pre-process the data before sending them to explain() ...  

An end-user can benefit from `vaeac`,` independence`, `ctree` dependency modeling approaches without applying one-hot encoding. **However, If I have a dataset, for example, Abalone, where the categorical feature is previously encoded**, can I use `vaeac`,` independence`, and `ctree` approaches in this setting?
Last but not least, I really appreciate your priceless time in advance. 

Kind regards,
A

**Comment by aliamini-uq** [comment]
Dear @LHBO,

I will be honored if you take a look at my problem. 

Kind regards,
A

**Comment by martinju** [comment]
Hi

You can use them, but you will get one shapley value per level in your categorical data, which does not really make sense, and will also increase the computational complexity unnecessarily . Thus, you should rather transform your data back to the original setup without one-hot-encoding and pass that to shapr using a prediction function which takes the original data as input. 

Hope this helps.

**Comment by aliamini-uq** [comment]
Many thanks for your help.
