### ISSUE TITLE
Comparison with orignal independence implementation of KernelSHAP

### ISSUE THREAD

**Issue by martinju** [NorskRegnesentral/shapr#59]
Create test that shows that (a special case of) our implementation of independence kernelSHAP gives the same results as Lundberg's implementations.

Do this in a Rmarkdown document? And put in in a folder under inst?
Link to the comparison from the Readme.

**Comment by nikolase90** [comment]
Sounds good! I think we should put this in a section of the vignette.

**Comment by martinju** [comment]
Sure!
